# site settings
title: Demo Website
subtitle: for teaching purposes
email: youremailaddress@gmail.com
description: Just learning some web stuff.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://imnotamember.github.io/ # the base hostname & protocol for your site
author: imnotanauthor
street_address: 1234 Somewhere Road
city: Lincoln
state: NE
zip_code: 00000
country: someplace
phone: 000-000-0000

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
